let tittle = "Baby Shark";
let line1 = "Baby shark, doo, doo, doo, doo, doo, doo";
let line2 = "Mommy shark, doo, doo, doo, doo, doo, doo";
let line2mommy = "Mommy shark";
let line3 = "Daddy shark, doo, doo, doo, doo, doo, doo";
let line3daddy = "Daddy shark";
let line4 = "Grandma shark, doo, doo, doo, doo, doo, doo";
let line4Grandma = "Grandma shark";
let line5 = "Grandpa shark, doo, doo, doo, doo, doo, doo";
let line5Grandpa = "Grandpa shark, doo, doo, doo, doo, doo, doo";
let line6 = "Let's go hunt, doo, doo, doo, doo, doo, doo";
let line6lets_go = "Let's go hunt";
let line7 = "Run away, doo, doo, doo, doo, doo, doo";
let line7run_way = "Run away";
let line8 = "Safe at last, doo, doo, doo, doo, doo, doo";
let line8Safe_at_least = "Safe at last";
let line9 = "It's the end, doo, doo, doo, doo, doo, doo";
let line9end = "It's the end";

console.log(tittle);
console.log(line1);
console.log(line1);
console.log(line1);
console.log(tittle);
console.log(line2);
console.log(line2);
console.log(line2);
console.log(line2mommy);
console.log(line3);
console.log(line3);
console.log(line3);
console.log(line3daddy);
console.log(line4);
console.log(line4);
console.log(line4);
console.log(line4Grandma);
console.log(line5);
console.log(line5);
console.log(line5);
console.log(line5Grandpa);
console.log(line6);
console.log(line6);
console.log(line6);
console.log(line6lets_go);
console.log(line7);
console.log(line7);
console.log(line7);
console.log(line7run_way);
console.log(line8);
console.log(line8);
console.log(line8);
console.log(line8Safe_at_least);
console.log(line9);
console.log(line9);
console.log(line9);
console.log(line9end);
